DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS posts2;

CREATE TABLE empresa (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    nome TEXT NOT NULL,
    telecom TEXT NOT NULL

);

CREATE TABLE escola (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    nome TEXT NOT NULL,
    grau TEXT NOT NULL,
    horario TEXT NOT NULL
);